sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER="--compiler=gcc-6" BUILD_TYPE="-c dbg"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER="--compiler=gcc-5" BUILD_TYPE="-c dbg"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER="--compiler=gcc-4.9" BUILD_TYPE="-c dbg"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            g++-4.9
            clang++-3.9
      env:
        - COMPILER="--compiler=clang-3.9" BUILD_TYPE="-c dbg"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            g++-4.9
            clang++-3.9
      env:
        - COMPILER="--compiler=clang-3.9" BUILD_TYPE="-c dbg"
        - COV="ON" COV_OPTION="--config=kcov --copt=-O2 --test_tag_filters=unittest"
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER="" BUILD_TYPE="-c opt"

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo add-apt-repository ppa:dreal/dreal -y;
      sudo apt update;
      sudo apt install autoconf automake bison coinor-libclp-dev flex libtool pkg-config libibex-dev;
      wget https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel_0.5.4-linux-x86_64.deb;
      sudo dpkg -i bazel_0.5.4-linux-x86_64.deb;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew install autoconf bazel libtool pkg-config dreal-deps/ibex/ibex || true;
    fi
  - if [ "${COV}" == "ON" ]; then
      git clone https://github.com/SimonKagstrom/kcov;
      cd kcov;
      mkdir build;
      cd build;
      cmake ../;
      make -j;
      sudo cp src/kcov /usr/bin/;
      cd ../../;
    fi

script:
  - |
    bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --local_resources=400,1,1.0 \
      //...  ${COMPILER} ${BUILD_TYPE} ${COV_OPTION}

notifications:
  recipients:
    - soonho.kong@gmail.com
  email:
    on_success: change
    on_failure: always
