name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos_catalina:
    name: macos catalina
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: ./setup/mac/install_prereqs.sh
        shell: zsh -efuo pipefail {0}
      - name: build and test
        run: bazel test //... -c dbg
  ubuntu_bionic:
    name: ubuntu bionic
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: sudo ./setup/ubuntu/18.04/install_prereqs.sh
        shell: bash
      - name: build and test
        run: bazel test //... -c dbg
  ubuntu_trusty:
    name: ubuntu trusty
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: sudo ./setup/ubuntu/16.04/install_prereqs.sh
        shell: bash
      - name: build and test
        run: bazel test //... -c dbg
